version: '3'

services:

  gobetween:
    restart: unless-stopped
    container_name: gobetween  
    image: gobetween_alpine:alpine_3.13.1-0.8.0 # yyyar/gobetween
    hostname: gobetween
    domainname: gobetween
    ports:
      - 8001:8001
    volumes:
      - ./conf:/etc/gobetween/conf/:rw
      
      


